### ISSUE TITLE
Need ideas on how to have multiple instances of whiteboard

### ISSUE THREAD

**Issue by mananjadhav** [mikhail-angelov/react-whiteboard#3]
I am thinking of using this whiteboard for one of the LMS projects and I am stuck at how to have multiple instances of the whiteboard (because Store is a singleton instance). 

Would you be able to throw some light on that? I also intend to then use it further to send data via Webrtc and use it in a video conference module.

**Comment by mikhail-angelov** [comment]
>multiple instances of the whiteboard (because Store is a singleton instance)
it is, but it's easy to make multiple instances
- in store.js - export class, not instance
- create store multiple times 
- profit :)

**Comment by mananjadhav** [comment]
Thanks for the insight. I figured :)

Best part about your code was Select and move shape. Cheers!
